/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRefundRouteImport } from './routes/cancellation-refund'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRefundRoute = CancellationRefundRouteImport.update({
  id: '/cancellation-refund',
  path: '/cancellation-refund',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cancellation-refund'
    | '/contact'
    | '/enquiry'
    | '/privacy-policy'
    | '/products'
    | '/shipping-policy'
    | '/terms-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation-refund'
    | '/contact'
    | '/enquiry'
    | '/privacy-policy'
    | '/products'
    | '/shipping-policy'
    | '/terms-conditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cancellation-refund'
    | '/contact'
    | '/enquiry'
    | '/privacy-policy'
    | '/products'
    | '/shipping-policy'
    | '/terms-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CancellationRefundRoute: typeof CancellationRefundRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-refund': {
      id: '/cancellation-refund'
      path: '/cancellation-refund'
      fullPath: '/cancellation-refund'
      preLoaderRoute: typeof CancellationRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CancellationRefundRoute: CancellationRefundRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
